### ISSUE TITLE
Possible mistake in font name: Corbal = Corbel?

### ISSUE THREAD

**Issue by bitterjug** [typora/theme.typora.io#10]
I can't find a font called Corbal, did you mean Corbel?
``` css
 h1,
 h2,
 h3,
 h4,
 h5,
 h6 {
     font-family: "Lucida Grande", "Corbal", Georgia, serif;
     font-weight: normal;
     clear: both;
     -ms-word-wrap: break-word;
     word-wrap: break-word;
     margin: 0;
     padding: 0;
 }
```
