### ISSUE TITLE
Feature Request: PDF Friendly Version of Academic Theme

### ISSUE THREAD

**Issue by Yuxin-Ren-SZ** [typora/theme.typora.io#242]
I notice that Acadmeic theme actaully have a colored background which prevent me from exporting it as PDF or print it as PDF. I'm currently working on an academic formatical simple academic paper. It would be much helpful if it can be directly export out as any major academic paper format such as MLA, Chicago, etc.

If it takes sometime or not very possible to have it exactly the same, a version without background color would still be much appreciated.

**Comment by rnd195** [comment]
Hey, I am not sure whether we have the same version of the Academic theme, but I can export a PDF file without an issue (
[see the attached PDF file](https://github.com/typora/typora-theme-gallery/files/7612618/export.pdf)).

However, this should be an easy fix regardless. Try opening the `academic.css` file in the themes folder and add `--bg-color: #ffffff;` to `:root` like so

```css
:root {
    --bg-color: #ffffff;
    --side-bar-bg-color: white;
    --window-border: none;
    --search-select-bg-color: #575c61;
    --active-file-bg-color: #f1f4f5;
    --item-hover-bg-color: #f1f4f5;
    --item-hover-text-color: black;
    --control-text-color: #555;
}
```

If that doesn't work, you may also try the [Paper](https://theme.typora.io/theme/paper/) theme, which is also fit for academia.
