### ISSUE TITLE
Minimalism Dark

### ISSUE THREAD

**Issue by triangulum** [typora/theme.typora.io#62]
The Articles view for Minimalism Dark has white-on-white text, making it unreadable.

The cause is most likely:

```css
#typora-quick-open-item {
    background-color: #FAFAFA;
    border-color: #FEFEFE #e5e5e5 #e5e5e5 #eee;
    border-style: solid;
    border-width: 1px;
}
```

Overall, this theme is still quite buggy. Some of the `font-family` definitions are also incorrect, leading to display issues.

The "regular" light version seems to be fine.
