### ISSUE TITLE
typora select bug using shift+command+left

### ISSUE THREAD

**Issue by hitzhangjie** [typora/theme.typora.io#72]
I came across a problem today, I changed the theme from github to quartz-milky.
When I position the cursor at the heading, pressing shift+command+left will select all text before cursor.

using theme github, it works well.

I think maybe quartz-milky caused this, but I like this theme very much, hope to find out what caused this. 

maybe it's typora's bug, but maybe we slightly changed this theme maybe much more quick.

**Comment by hitzhangjie** [comment]
![image](https://user-images.githubusercontent.com/3725760/55634289-c4617680-57f0-11e9-8ac0-e90ad6636f10.png)

After I commented out theses lines, it works.

**Comment by hitzhangjie** [comment]
it is caused by display property, I changed it like following, now it works.
```css
   h1::before,                                                                            
   h2::before,                                                                            
   h3::before {                                                                           
     font-weight: 400;                                                                    
     /*text-align: right;*/                                                               
     /*width: 5ch;*/                                                                      
     /*padding-right: 1ch;*/                                                              
     /*margin-left: -5ch;*/                                                               
     color: var(--accent-color);                                                          
     /*display: inline-block;*/                                                           
     position: absolute;                                                                  
     right: calc(100% + 10px);                                                                                                                                                       
   } 
```
